<?php
$MYSQL_HOST = "localhost";
$MYSQL_DATABASE  = "21vek";
$MYSQL_USER  = "root";
$MYSQL_PASSWORD  = "";

$TELEGRAM_BOT_TOKEN = "6327259616:AAFJwRW-awlfQ4UUMvAonAvXmNXen_kvREs";
$TELEGRAM_CHAT_ID = "-4122430733";

$mysql = new mysqli($MYSQL_HOST, $MYSQL_USER, $MYSQL_PASSWORD, $MYSQL_DATABASE);